apiVersion: v1
kind: Pod
metadata:
  name: pap-download-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
  - name: pap-processing
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    env:
    - name: REPO_PATH
      value: /opt/repo/papGAN
    command:
    - "bash"
    - "-c"
    args:
    - |
      # --- User and Environment Setup ---
      echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
      
      # --- Git Repository Update ---
      echo "Cloning Git repository..."
      cd /opt/repo
      git clone --single-branch -b main https://github.com/tsereda/papGAN
      cd ${REPO_PATH}
      echo "Git repository cloned."
      
      # --- Download dataset ---
      echo "Downloading dataset..."
      cd ${REPO_PATH}
      # Install gdown for Google Drive downloads
      pip install gdown
      
      # Download the dataset from Google Drive
      gdown --id 1yeHKqXVf9YhS6FAqVGezKrSaNGp6v-xX -O /data/isbi2025-ps3c-train-dataset.zip
      
      # Unzip the dataset 
      echo "Unzipping dataset..."
      unzip -q /data/isbi2025-ps3c-train-dataset.zip -d ${REPO_PATH}
      
      # --- Run preprocessing ---
      echo "Running preprocessing..."
      cd ${REPO_PATH}
      # Install any additional requirements
      pip install -r pytorch-CycleGAN-and-pix2pix/requirements.txt
      
      # Run the preprocessing script
      python preprocess.py --source_dir ${REPO_PATH}/isbi2025-ps3c-train-dataset
      
      # Copy the processed data to the PVC for persistence
      echo "Copying processed data to persistent storage..."
      tar -czvf /data/cyclegan_processed_data.tar.gz cyclegan_dataset_256_split
      
      echo "All processing completed. Your data is ready at /data/cyclegan_processed_data.tar.gz"

    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: pap-data-volume
      mountPath: /data
    - name: dshm
      mountPath: /dev/shm
    resources:
      limits:
        memory: 16Gi
        cpu: "8"
      requests:
        memory: 12Gi
        cpu: "6"
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: pap-data-volume
    persistentVolumeClaim:
      claimName: pap-data
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 4Gi
  restartPolicy: Never