apiVersion: v1
kind: Pod
metadata:
  name: pap-processing-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
  - name: pap-processing
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    env:
    - name: REPO_PATH
      value: /opt/repo/papGAN
    command:
    - "bash"
    - "-c"
    args:
    - |
      # --- User and Environment Setup ---
      echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"

      # --- Git Repository Update ---
      echo "Updating Git repository..."
      cd ${REPO_PATH}
      git pull origin main || { echo "Failed to update git repository"; exit 1; }
      echo "Git repository updated."

      echo "Pod is running. Connect with: kubectl exec -it <pod-name> -- bash"
      echo "Sleeping indefinitely. Use Ctrl+C to terminate."
      
      sleep infinity


    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: pap-data-volume
      mountPath: /data
    - name: dshm
      mountPath: /dev/shm

    resources:
      limits:
        memory: 36Gi
        cpu: "12"
        nvidia.com/a100: "1"
      requests:
        memory: 30Gi
        cpu: "10"
        nvidia.com/a100: "1"

  initContainers:
  - name: init-git-repo
    image: alpine/git
    args:
    - clone
    - --single-branch
    - -b
    - main
    - https://github.com/tsereda/papGAN #Change this
    - /opt/repo/papGAN
    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    resources:
      limits:
        memory: 307Mi
        cpu: 240m
      requests:
        memory: 256Mi
        cpu: 200m

  volumes:
  - name: git-repo
    emptyDir: {}
  - name: pap-data-volume
    persistentVolumeClaim:
      claimName: pap-data
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 8Gi

  restartPolicy: Never