apiVersion: v1
kind: Pod
metadata:
  name: pap-preprocess-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
    - name: pap-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      env:
        - name: REPO_PATH
          value: /opt/repo/papGAN
      command:
        - "bash"
        - "-c"
      args:
        - |
          # --- User and Environment Setup ---
          echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
          
          # --- Git Repository Update ---
          echo "Cloning Git repository..."
          cd /opt/repo
          git clone --single-branch -b main https://github.com/tsereda/papGAN
          cd ${REPO_PATH}
          echo "Git repository cloned."
          
          # --- Install dependencies ---
          echo "Installing dependencies for preprocessing..."
          cd ${REPO_PATH}
          
          # Clone CycleGAN repository if needed
          if [ ! -d "${REPO_PATH}/pytorch-CycleGAN-and-pix2pix" ]; then
            git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git
          fi
          
          # Install requirements
          pip install -r pytorch-CycleGAN-and-pix2pix/requirements.txt
          
          # Install any additional requirements for preprocessing
          pip install opencv-python pillow numpy matplotlib
          
          # --- Run preprocessing ---
          echo "Running preprocessing..."
          cd ${REPO_PATH}
          
          # Run the preprocessing script
          python preprocess.py --source_dir /data/isbi2025-ps3c-train-dataset
          
          # Copy the processed data to the PVC for persistence
          echo "Archiving processed data to persistent storage..."
          tar -czvf /data/cyclegan_processed_data.tar.gz cyclegan_dataset_256_split
          
          echo "Preprocessing completed. Your data is ready at /data/cyclegan_processed_data.tar.gz"
      volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: pap-data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      resources:
        limits:
          memory: 16Gi
          cpu: "8"
          nvidia.com/gpu: "1" # Add GPU if preprocessing needs it
        requests:
          memory: 12Gi
          cpu: "6"
  volumes:
    - name: git-repo
      emptyDir: {}
    - name: pap-data-volume
      persistentVolumeClaim:
        claimName: pap-data
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 4Gi
  restartPolicy: Never