apiVersion: batch/v1
kind: Job
metadata:
  name: pap-download-job
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
      containers:
      - name: pap-download
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
        env:
        - name: REPO_PATH
          value: /opt/repo/papGAN
        command:
        - "bash"
        - "-c"
        args:
        - |
          # --- User and Environment Setup ---
          echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
          # --- Git Repository Update ---
          echo "Cloning Git repository..."
          cd /opt/repo
          git clone --single-branch -b main https://github.com/tsereda/papGAN
          cd ${REPO_PATH}
          echo "Git repository cloned."
          # --- Download dataset ---
          echo "Downloading dataset..."
          cd ${REPO_PATH}
          # Install gdown for Google Drive downloads
          pip install gdown
          # Download the dataset from Google Drive
          # gdown 1q5czzLDE_lQLJlko5Zpb10lUbPwVqkHW -O /data/isbi2025-ps3c-train-dataset.7z
          mv /data/isbi2025-ps3c-train-dataset.zip /data/isbi2025-ps3c-train-dataset.7z
          echo "Download and extraction completed. Dataset is available at /data/isbi2025-ps3c-train-dataset.7z"
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: pap-data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            memory: 24Gi
            cpu: "24"
          requests:
            memory: 20Gi
            cpu: "20"
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: pap-data-volume
        persistentVolumeClaim:
          claimName: pap-data
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
      restartPolicy: Never