apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pap-data
spec:
  accessModes:
    - ReadWriteOnce  # ReadWriteMany if multiple pods need access at once
  resources:
    requests:
      storage: 50Gi  # Adjust as needed