apiVersion: v1
kind: Pod
metadata:
  name: preprocess-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
  - name: pap-processing
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    env:
    - name: REPO_PATH
      value: /opt/repo/papGAN
    command:
    - "bash"
    - "-c"
    args:
    - |
      # --- User and Environment Setup ---
      echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
      
      # --- Git Repository Update ---
      echo "Cloning Git repository..."
      cd /opt/repo
      git clone --single-branch -b main https://github.com/tsereda/papGAN
      cd ${REPO_PATH}
      echo "Git repository cloned."
      
      sudo apt-get update && sudo apt-get install -y p7zip-full
      
      # --- Download dataset ---
      echo "Extracting..."
      
      7z x /data/isbi2025-ps3c-train-dataset.7z -o/opt/repo/papGAN/
      
      # --- Run preprocessing ---
      echo "Running preprocessing..."
      cd ${REPO_PATH}
  
      
      # Run the preprocessing script with the extracted dataset path
      echo "Running preprocess.py with: --source_dir /opt/repo/papGAN/isbi2025-ps3c-train-dataset"
      python preprocess.py --source_dir /opt/repo/papGAN/isbi2025-ps3c-train-dataset
      
      echo "Archiving processed data with parallel compression..."
      sudo apt-get install -y zstd
      tar -cf - cyclegan_dataset_256_split | zstd -T12 -7 > /data/cyclegan_processed_data.tar.zst
      
      echo "Preprocessing process completed. Data should be at /data/cyclegan_processed_data.tar.zst"
      ls -hf /data/
      sleep infinity

    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: pap-data-volume
      mountPath: /data
    - name: dshm
      mountPath: /dev/shm
    resources:
      requests:
        memory: 20Gi
        cpu: "10"
      limits:
        memory: 24Gi
        cpu: "12"
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: pap-data-volume
    persistentVolumeClaim:
      claimName: pap-data
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 20Gi