apiVersion: v1
kind: Pod
metadata:
  name: preprocess-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 100
    fsGroup: 100
  containers:
  - name: pap-processing
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    env:
    - name: REPO_PATH
      value: /opt/repo/papGAN
    command:
    - "bash"
    - "-c"
    args:
    - |
      # --- User and Environment Setup ---
      echo "Running as user: $(whoami), UID: $(id -u), GID: $(id -g)"
      
      # --- Git Repository Update ---
      echo "Cloning Git repository..."
      cd /opt/repo
      git clone --single-branch -b main https://github.com/tsereda/papGAN
      cd ${REPO_PATH}
      git clone https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.git
      echo "Git repositories cloned."
      
      sudo apt-get update && sudo apt-get install -y p7zip-full
      pip install dominate pytorch_fid
      
      # --- Download dataset ---
      echo "Extracting..."
      
      tar -x -I "zstd -d -T0" -f /data/cyclegan_processed_data.tar.zst -C ${REPO_PATH}
      mkdir checkpoints
      mkdir checkpoints/unhealthy
      cp /data/latest_net_G_B.pth checkpoints/unhealthy/latest_net_G.pth


      python pytorch-CycleGAN-and-pix2pix/test.py   --dataroot ./cyclegan_dataset_256_split/test_healthy   --name unhealthy   --model test   --no_dropout   --num_test 1162   --results_dir ./results_20k   --direction AtoB
      python3 restruture_cyclegan_output.py --input_folder results_20k/unhealthy/test_latest/images/

      pip install torchmetrics[image] tqdm pillow

      python fid.py --real-healthy cyclegan_dataset_256_split/valA --real-unhealthy cyclegan_dataset_256_split/valB --generated results_20k/unhealthy/test_latest/generated --device cuda --batch-size 64
      cp fid_results.txt /data/fid_results.txt
      sleep infinity

    volumeMounts:
    - name: git-repo
      mountPath: /opt/repo
    - name: pap-data-volume
      mountPath: /data
    - name: dshm
      mountPath: /dev/shm
    resources:
      requests:
        memory: 20Gi
        cpu: "10"
        nvidia.com/gpu: "2"
      limits:
        memory: 24Gi
        cpu: "12"
        nvidia.com/gpu: "2"
  volumes:
  - name: git-repo
    emptyDir: {}
  - name: pap-data-volume
    persistentVolumeClaim:
      claimName: pap-data
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 20Gi