apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pap-data-many
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi