apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: mnist-tune-job
spec:
  entrypoint: |
    pip install torch torchvision wandb
    python /tmp/mnist_tune.py
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 300
  # Use rayClusterSelector instead of rayClusterSpec.rayClusterRef
  rayClusterSelector:
    matchLabels:
      name: mnist-raycluster